version: '2'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    networks:
      - bridge 
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=changeme
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - bridge 
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
volumes:
  influxdb-storage:
  grafana-storage:

networks:
  bridge:
