version: '3.7'

services:

  nodered:
    image: nodered/node-red:latest
    container_name: NodeRed
    user: node-red
    restart: unless-stopped
    group_add:
      - dialout
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    volumes:
      - 'node-red-data:/data'
    ports:
      - "1880:1880"

volumes:
  node-red-data:

