version: '2.0'

services:

  basicstation:
    
    image: xoseperez/basicstation:v2
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host

    environment:

      MODEL: "RAK2287"
      INTERFACE: "SPI"
      GW_RESET_GPIO: 17
      GW_POWER_EN_GPIO: 0
      GW_POWER_EN_LOGIC: 1
      DEVICE: "/dev/spidev0.0"
      GATEWAY_EUI: "E45F01FFFE51B772"
      # Using LNS protocol: define a custom LNS server
      TC_URI: "wss://localhost:8887"
      # Using LNS protocol: if you use a server other than TTN, you will have to provide the certificate for that server.
      TC_TRUST: "-----BEGIN CERTIFICATE-----MIIDxDCCAqygAwIBAgIULKP9/d102/IvyO5RhDOllXLB7TEwDQYJKoZIhvcNAQELBQAwaDELMAkGA1UEBhMCRVMxEjAQBgNVBAgTCUNhdGFsdW55YTESMBAGA1UEBxMJQmFyY2Vsb25hMRYwFAYDVQQKEw1UVE4gQ2F0YWx1bnlhMRkwFwYDVQQDExBUVE4gQ2F0YWx1bnlhIENBMB4XDTIyMDYxNTA4MzYwMFoXDTI3MDYxNDA4MzYwMFowaDELMAkGA1UEBhMCRVMxEjAQBgNVBAgTCUNhdGFsdW55YTESMBAGA1UEBxMJQmFyY2Vsb25hMRYwFAYDVQQKEw1UVE4gQ2F0YWx1bnlhMRkwFwYDVQQDExBUVE4gQ2F0YWx1bnlhIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA586x/hUE93Q46nSMSIA4sIbkrqV9MBv+HzxKTvlA5KI43QOh0uhFpKiwzLU9twVVn2NqnIUXVkTputPUG6NDzTw7Cc4lJSv21QswrmHqlzjlSyWpn9+MgxDngwCZuotHlgeMNhB4N2HonOgK6BFMjQGAcIoZlLWDvXfgjSn5rD52hi/8s7MtVHTsLJigx0od822ptaxK8MgQrsIjWvh9rruJN2xPJNSbbsU42DeojdRxuBaii0QfSQK8ienPTJgrujjr8nClp32/elA8Up9L0yffssl4Kx9ggTsI5YqkArA7ecSitSZkUh3UAWNb8b1fwACSahmDXBVJtKH9XWI6tQIDAQABo2YwZDAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBAjAdBgNVHQ4EFgQUrEXxeuVBKPMztM6lgy/4MPUe5ocwHwYDVR0jBBgwFoAUrEXxeuVBKPMztM6lgy/4MPUe5ocwDQYJKoZIhvcNAQELBQADggEBANwm9NnrAZQBgjFkt0TmwF4lymuJPGg9I0kEOfWYSmyVfTAr9NaY/c+rQtH68z9VN+RumX3juAt74SsWR2OKZdtoTm7/yDieG9KMLj2Bbi4FjXSAPQqr1MMx5Ggic9NLdK360vvHMoIRtygmVP3ZnsmzVLHqTdBxZEurD3TlMZ/ffsFiYnG+gqsGvVHrSQX91nWmY/rZrkPGXInNMPz+nAjNyeFnvt8VTHtXvDGgCJSDEJTdirk+kNvKeeDcp+LQCwFCRPwgWqWM/5WCtIXdqB2vGWz3P9Jvq+p/UWrG6+ShjTK+LHckW0M5/2wfm6Lvqhsa4n6yT9HqC93mzKqnX2U=-----END CERTIFICATE-----"
      # Using LNS protocol: finally, you need to create a KEY for the gateway and provide it here:
      TC_KEY: "NNSXS.DQZBZI225IAPCAVD2XLZB7O7Y373CDLKLYIF4FA.XCOVT3GJ7JL677RK5ZK7AZUGR7PO74ZUF4BXVLMM4WBUXLINFFVA"

  2g4-packet-forwarder:
    image: xoseperez/2g4-packet-forwarder:latest
    container_name: 2g4-packet-forwarder
    restart: unless-stopped
    devices:
      - /dev/ttyAMAO

    environment:

      # If you have the concentrator connected to a different port you can define it this way
      #DEVICE: "/dev/ttyS0"

      # The default LNS server is the European TTN server.
      # If you still want to use TTN but a different region you can set it this way:
      #TTN_REGION: "eu1"

      # Or you can set a completely different LNS server.
      SERVER_HOST: localhost
      SERVER_PORT: 1700

      # If you want the gateway to report a specific lat/lon/alt you can set them this way:
      #GPS_LATITUDE: 41.42
      #GPS_LONGITUDE: 2.12
      #GPS_ALTITUDE: 0
