version: '2.4'

services:
  
  tailscaled:
    build:
      context: tailscale
    container_name: tailscaled
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /var/lib:/var/lib 
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    environment:
      - TS_AUTH_KEY=tskey-your-key-here
